services:
  mkdocs:
    build: .
    container_name: auth-docs
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml

