site_name: User Auth Documentation
site_description: Documentation for Keycloak, React, and FastAPI Auth Setup
site_author: Arjun 

repo_name: arjunraghurama/learn-user-auth
repo_url: https://github.com/arjunraghurama/learn-user-auth
edit_uri: edit/main/docs/


theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    

nav:
  - Home: index.md
  - Introduction to Keycloak: keycloak.md
  - Authentication Protocols: auth-types.md
  - OAuth Grant Types: oauth-grants.md
  - Authentication Flow: authentication-flow.md
  - Backend Token Verification: backend-verification.md
  - Nginx Reverse Proxy: nginx-proxy.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arjunraghurama/learn-user-auth

# plugins:
#     - search
#     - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
